export const features = [
	{
		title: "Quality",
		desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Harum totam sed ducimus vel? Repudiandae eveniet, expedita ipsam adipisci quo aut velit totam amet eligendi. Tenetur facilis eligendi repudiandae aut eos!",
		image: "/assets/features/tasty.png",
	},
	{
		title: "Fast Delivery",
		desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Harum totam sed ducimus vel? Repudiandae eveniet, expedita ipsam adipisci quo aut velit totam amet eligendi. Tenetur facilis eligendi repudiandae aut eos!",
		image: "/assets/features/delivery-bike.png",
	},
	{
		title: "Home Delivery",
		desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Harum totam sed ducimus vel? Repudiandae eveniet, expedita ipsam adipisci quo aut velit totam amet eligendi. Tenetur facilis eligendi repudiandae aut eos!",
		image: "/assets/features/delivery-man.png",
	},
];

export const foodItems = [
	{
		id: 1,
		price: 68.7876,
		title: "Breakfast1",
		desc: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Quisquam tempora minima iure delectus tempore, voluptates, tenetur iste magni aliquid maiores maxime modi ipsum a laboriosam. Possimus eaque dolorem, at expedita soluta illum, unde quam, commodi numquam dolorum nemo ducimus ullam eos tempora nisi. Ratione, minima deleniti explicabo tempora eius, dolores quos vel ex eaque quas itaque. Obcaecati, tempora voluptatem! Maiores, facere recusandae. Natus recusandae, nobis placeat adipisci quidem unde sint ex atque sequi eveniet, eius illo modi dolorem repellat reiciendis beatae suscipit magni minima excepturi libero voluptatum molestiae. Autem eius nihil, architecto ex vero illo tenetur? Consequatur ducimus possimus ab.",
		category: "breakfast",
		ingredients: ["butter, bread, egg"],
		image: "/assets/Breakfast/breakfast2.png",
	},
	{
		id: 2,
		price: 97.0716,
		title: "Breakfast2",
		desc: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Quisquam tempora minima iure delectus tempore, voluptates, tenetur iste magni aliquid maiores maxime modi ipsum a laboriosam. Possimus eaque dolorem, at expedita soluta illum, unde quam, commodi numquam dolorum nemo ducimus ullam eos tempora nisi. Ratione, minima deleniti explicabo tempora eius, dolores quos vel ex eaque quas itaque. Obcaecati, tempora voluptatem! Maiores, facere recusandae. Natus recusandae, nobis placeat adipisci quidem unde sint ex atque sequi eveniet, eius illo modi dolorem repellat reiciendis beatae suscipit magni minima excepturi libero voluptatum molestiae. Autem eius nihil, architecto ex vero illo tenetur? Consequatur ducimus possimus ab.",
		category: "breakfast",
		ingredients: ["butter, bread, egg"],
		image: "/assets/Breakfast/breakfast2.png",
	},
	{
		id: 3,
		price: 65.0451,
		title: "Breakfast3",
		desc: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Quisquam tempora minima iure delectus tempore, voluptates, tenetur iste magni aliquid maiores maxime modi ipsum a laboriosam. Possimus eaque dolorem, at expedita soluta illum, unde quam, commodi numquam dolorum nemo ducimus ullam eos tempora nisi. Ratione, minima deleniti explicabo tempora eius, dolores quos vel ex eaque quas itaque. Obcaecati, tempora voluptatem! Maiores, facere recusandae. Natus recusandae, nobis placeat adipisci quidem unde sint ex atque sequi eveniet, eius illo modi dolorem repellat reiciendis beatae suscipit magni minima excepturi libero voluptatum molestiae. Autem eius nihil, architecto ex vero illo tenetur? Consequatur ducimus possimus ab.",
		category: "breakfast",
		ingredients: ["butter, bread, egg"],
		image: "/assets/Breakfast/breakfast3.png",
	},
	{
		id: 4,
		price: 92.6065,
		title: "Breakfast4",
		desc: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Quisquam tempora minima iure delectus tempore, voluptates, tenetur iste magni aliquid maiores maxime modi ipsum a laboriosam. Possimus eaque dolorem, at expedita soluta illum, unde quam, commodi numquam dolorum nemo ducimus ullam eos tempora nisi. Ratione, minima deleniti explicabo tempora eius, dolores quos vel ex eaque quas itaque. Obcaecati, tempora voluptatem! Maiores, facere recusandae. Natus recusandae, nobis placeat adipisci quidem unde sint ex atque sequi eveniet, eius illo modi dolorem repellat reiciendis beatae suscipit magni minima excepturi libero voluptatum molestiae. Autem eius nihil, architecto ex vero illo tenetur? Consequatur ducimus possimus ab.",
		category: "breakfast",
		ingredients: ["butter, bread, egg"],
		image: "/assets/Breakfast/breakfast4.png",
	},
	{
		id: 5,
		price: 24.6418,
		title: "Breakfast5",
		desc: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Quisquam tempora minima iure delectus tempore, voluptates, tenetur iste magni aliquid maiores maxime modi ipsum a laboriosam. Possimus eaque dolorem, at expedita soluta illum, unde quam, commodi numquam dolorum nemo ducimus ullam eos tempora nisi. Ratione, minima deleniti explicabo tempora eius, dolores quos vel ex eaque quas itaque. Obcaecati, tempora voluptatem! Maiores, facere recusandae. Natus recusandae, nobis placeat adipisci quidem unde sint ex atque sequi eveniet, eius illo modi dolorem repellat reiciendis beatae suscipit magni minima excepturi libero voluptatum molestiae. Autem eius nihil, architecto ex vero illo tenetur? Consequatur ducimus possimus ab.",
		category: "breakfast",
		ingredients: ["butter, bread, egg"],
		image: "/assets/Breakfast/breakfast5.png",
	},
	{
		id: 6,
		price: 64.1733,
		title: "Breakfast6",
		desc: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Quisquam tempora minima iure delectus tempore, voluptates, tenetur iste magni aliquid maiores maxime modi ipsum a laboriosam. Possimus eaque dolorem, at expedita soluta illum, unde quam, commodi numquam dolorum nemo ducimus ullam eos tempora nisi. Ratione, minima deleniti explicabo tempora eius, dolores quos vel ex eaque quas itaque. Obcaecati, tempora voluptatem! Maiores, facere recusandae. Natus recusandae, nobis placeat adipisci quidem unde sint ex atque sequi eveniet, eius illo modi dolorem repellat reiciendis beatae suscipit magni minima excepturi libero voluptatum molestiae. Autem eius nihil, architecto ex vero illo tenetur? Consequatur ducimus possimus ab.",
		category: "breakfast",
		ingredients: ["butter, bread, egg"],
		image: "/assets/Breakfast/breakfast6.png",
	},
	{
		id: 7,
		price: 74.9905,
		title: "Lunch1",
		desc: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Quisquam tempora minima iure delectus tempore, voluptates, tenetur iste magni aliquid maiores maxime modi ipsum a laboriosam. Possimus eaque dolorem, at expedita soluta illum, unde quam, commodi numquam dolorum nemo ducimus ullam eos tempora nisi. Ratione, minima deleniti explicabo tempora eius, dolores quos vel ex eaque quas itaque. Obcaecati, tempora voluptatem! Maiores, facere recusandae. Natus recusandae, nobis placeat adipisci quidem unde sint ex atque sequi eveniet, eius illo modi dolorem repellat reiciendis beatae suscipit magni minima excepturi libero voluptatum molestiae. Autem eius nihil, architecto ex vero illo tenetur? Consequatur ducimus possimus ab.",
		category: "lunch",
		ingredients: ["butter, bread, egg"],
		image: "/assets/lunch/lunch1.png",
	},
	{
		id: 8,
		price: 48.8493,
		title: "Lunch2",
		desc: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Quisquam tempora minima iure delectus tempore, voluptates, tenetur iste magni aliquid maiores maxime modi ipsum a laboriosam. Possimus eaque dolorem, at expedita soluta illum, unde quam, commodi numquam dolorum nemo ducimus ullam eos tempora nisi. Ratione, minima deleniti explicabo tempora eius, dolores quos vel ex eaque quas itaque. Obcaecati, tempora voluptatem! Maiores, facere recusandae. Natus recusandae, nobis placeat adipisci quidem unde sint ex atque sequi eveniet, eius illo modi dolorem repellat reiciendis beatae suscipit magni minima excepturi libero voluptatum molestiae. Autem eius nihil, architecto ex vero illo tenetur? Consequatur ducimus possimus ab.",
		category: "lunch",
		ingredients: ["butter, bread, egg"],
		image: "/assets/lunch/lunch2.png",
	},
	{
		id: 9,
		price: 71.1474,
		title: "Lunch3",
		desc: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Quisquam tempora minima iure delectus tempore, voluptates, tenetur iste magni aliquid maiores maxime modi ipsum a laboriosam. Possimus eaque dolorem, at expedita soluta illum, unde quam, commodi numquam dolorum nemo ducimus ullam eos tempora nisi. Ratione, minima deleniti explicabo tempora eius, dolores quos vel ex eaque quas itaque. Obcaecati, tempora voluptatem! Maiores, facere recusandae. Natus recusandae, nobis placeat adipisci quidem unde sint ex atque sequi eveniet, eius illo modi dolorem repellat reiciendis beatae suscipit magni minima excepturi libero voluptatum molestiae. Autem eius nihil, architecto ex vero illo tenetur? Consequatur ducimus possimus ab.",
		category: "lunch",
		ingredients: ["butter, bread, egg"],
		image: "/assets/lunch/lunch3.png",
	},
	{
		id: 10,
		price: 75.5968,
		title: "Lunch4",
		desc: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Quisquam tempora minima iure delectus tempore, voluptates, tenetur iste magni aliquid maiores maxime modi ipsum a laboriosam. Possimus eaque dolorem, at expedita soluta illum, unde quam, commodi numquam dolorum nemo ducimus ullam eos tempora nisi. Ratione, minima deleniti explicabo tempora eius, dolores quos vel ex eaque quas itaque. Obcaecati, tempora voluptatem! Maiores, facere recusandae. Natus recusandae, nobis placeat adipisci quidem unde sint ex atque sequi eveniet, eius illo modi dolorem repellat reiciendis beatae suscipit magni minima excepturi libero voluptatum molestiae. Autem eius nihil, architecto ex vero illo tenetur? Consequatur ducimus possimus ab.",
		category: "lunch",
		ingredients: ["butter, bread, egg"],
		image: "/assets/lunch/lunch4.png",
	},
	{
		id: 11,
		price: 86.3351,
		title: "Lunch5",
		desc: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Quisquam tempora minima iure delectus tempore, voluptates, tenetur iste magni aliquid maiores maxime modi ipsum a laboriosam. Possimus eaque dolorem, at expedita soluta illum, unde quam, commodi numquam dolorum nemo ducimus ullam eos tempora nisi. Ratione, minima deleniti explicabo tempora eius, dolores quos vel ex eaque quas itaque. Obcaecati, tempora voluptatem! Maiores, facere recusandae. Natus recusandae, nobis placeat adipisci quidem unde sint ex atque sequi eveniet, eius illo modi dolorem repellat reiciendis beatae suscipit magni minima excepturi libero voluptatum molestiae. Autem eius nihil, architecto ex vero illo tenetur? Consequatur ducimus possimus ab.",
		category: "lunch",
		ingredients: ["butter, bread, egg"],
		image: "/assets/lunch/lunch5.png",
	},
	{
		id: 12,
		price: 76.905,
		title: "Lunch6",
		desc: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Quisquam tempora minima iure delectus tempore, voluptates, tenetur iste magni aliquid maiores maxime modi ipsum a laboriosam. Possimus eaque dolorem, at expedita soluta illum, unde quam, commodi numquam dolorum nemo ducimus ullam eos tempora nisi. Ratione, minima deleniti explicabo tempora eius, dolores quos vel ex eaque quas itaque. Obcaecati, tempora voluptatem! Maiores, facere recusandae. Natus recusandae, nobis placeat adipisci quidem unde sint ex atque sequi eveniet, eius illo modi dolorem repellat reiciendis beatae suscipit magni minima excepturi libero voluptatum molestiae. Autem eius nihil, architecto ex vero illo tenetur? Consequatur ducimus possimus ab.",
		category: "lunch",
		ingredients: ["butter, bread, egg"],
		image: "/assets/lunch/lunch6.png",
	},
	{
		id: 13,
		price: 29.0499,
		title: "Dinner1",
		desc: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Quisquam tempora minima iure delectus tempore, voluptates, tenetur iste magni aliquid maiores maxime modi ipsum a laboriosam. Possimus eaque dolorem, at expedita soluta illum, unde quam, commodi numquam dolorum nemo ducimus ullam eos tempora nisi. Ratione, minima deleniti explicabo tempora eius, dolores quos vel ex eaque quas itaque. Obcaecati, tempora voluptatem! Maiores, facere recusandae. Natus recusandae, nobis placeat adipisci quidem unde sint ex atque sequi eveniet, eius illo modi dolorem repellat reiciendis beatae suscipit magni minima excepturi libero voluptatum molestiae. Autem eius nihil, architecto ex vero illo tenetur? Consequatur ducimus possimus ab.",
		category: "dinner",
		ingredients: ["butter, bread, egg"],
		image: "/assets/Dinner/dinner1.png",
	},
	{
		id: 14,
		price: 80.9222,
		title: "Dinner2",
		desc: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Quisquam tempora minima iure delectus tempore, voluptates, tenetur iste magni aliquid maiores maxime modi ipsum a laboriosam. Possimus eaque dolorem, at expedita soluta illum, unde quam, commodi numquam dolorum nemo ducimus ullam eos tempora nisi. Ratione, minima deleniti explicabo tempora eius, dolores quos vel ex eaque quas itaque. Obcaecati, tempora voluptatem! Maiores, facere recusandae. Natus recusandae, nobis placeat adipisci quidem unde sint ex atque sequi eveniet, eius illo modi dolorem repellat reiciendis beatae suscipit magni minima excepturi libero voluptatum molestiae. Autem eius nihil, architecto ex vero illo tenetur? Consequatur ducimus possimus ab.",
		category: "dinner",
		ingredients: ["butter, bread, egg"],
		image: "/assets/Dinner/dinner2.png",
	},
	{
		id: 15,
		price: 39.0287,
		title: "Dinner3",
		desc: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Quisquam tempora minima iure delectus tempore, voluptates, tenetur iste magni aliquid maiores maxime modi ipsum a laboriosam. Possimus eaque dolorem, at expedita soluta illum, unde quam, commodi numquam dolorum nemo ducimus ullam eos tempora nisi. Ratione, minima deleniti explicabo tempora eius, dolores quos vel ex eaque quas itaque. Obcaecati, tempora voluptatem! Maiores, facere recusandae. Natus recusandae, nobis placeat adipisci quidem unde sint ex atque sequi eveniet, eius illo modi dolorem repellat reiciendis beatae suscipit magni minima excepturi libero voluptatum molestiae. Autem eius nihil, architecto ex vero illo tenetur? Consequatur ducimus possimus ab.",
		category: "dinner",
		ingredients: ["butter, bread, egg"],
		image: "/assets/Dinner/dinner3.png",
	},
	{
		id: 16,
		price: 40.1177,
		title: "Dinner4",
		desc: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Quisquam tempora minima iure delectus tempore, voluptates, tenetur iste magni aliquid maiores maxime modi ipsum a laboriosam. Possimus eaque dolorem, at expedita soluta illum, unde quam, commodi numquam dolorum nemo ducimus ullam eos tempora nisi. Ratione, minima deleniti explicabo tempora eius, dolores quos vel ex eaque quas itaque. Obcaecati, tempora voluptatem! Maiores, facere recusandae. Natus recusandae, nobis placeat adipisci quidem unde sint ex atque sequi eveniet, eius illo modi dolorem repellat reiciendis beatae suscipit magni minima excepturi libero voluptatum molestiae. Autem eius nihil, architecto ex vero illo tenetur? Consequatur ducimus possimus ab.",
		category: "dinner",
		ingredients: ["butter, bread, egg"],
		image: "/assets/Dinner/dinner4.png",
	},
	{
		id: 17,
		price: 71.8267,
		title: "Dinner5",
		desc: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Quisquam tempora minima iure delectus tempore, voluptates, tenetur iste magni aliquid maiores maxime modi ipsum a laboriosam. Possimus eaque dolorem, at expedita soluta illum, unde quam, commodi numquam dolorum nemo ducimus ullam eos tempora nisi. Ratione, minima deleniti explicabo tempora eius, dolores quos vel ex eaque quas itaque. Obcaecati, tempora voluptatem! Maiores, facere recusandae. Natus recusandae, nobis placeat adipisci quidem unde sint ex atque sequi eveniet, eius illo modi dolorem repellat reiciendis beatae suscipit magni minima excepturi libero voluptatum molestiae. Autem eius nihil, architecto ex vero illo tenetur? Consequatur ducimus possimus ab.",
		category: "dinner",
		ingredients: ["butter, bread, egg"],
		image: "/assets/Dinner/dinner5.png",
	},
	{
		id: 18,
		price: 78.8614,
		title: "Dinner6",
		desc: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Quisquam tempora minima iure delectus tempore, voluptates, tenetur iste magni aliquid maiores maxime modi ipsum a laboriosam. Possimus eaque dolorem, at expedita soluta illum, unde quam, commodi numquam dolorum nemo ducimus ullam eos tempora nisi. Ratione, minima deleniti explicabo tempora eius, dolores quos vel ex eaque quas itaque. Obcaecati, tempora voluptatem! Maiores, facere recusandae. Natus recusandae, nobis placeat adipisci quidem unde sint ex atque sequi eveniet, eius illo modi dolorem repellat reiciendis beatae suscipit magni minima excepturi libero voluptatum molestiae. Autem eius nihil, architecto ex vero illo tenetur? Consequatur ducimus possimus ab.",
		category: "dinner",
		ingredients: ["butter, bread, egg"],
		image: "/assets/Dinner/dinner6.png",
	},
];
